### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by snake97123** [snake97123/furima-32028#9]
## URL
https://furima-32028.herokuapp.com/
## Basic認証のIDとパスワード
ID:snake
パスワード:0405
## 出品者のメールアドレスとパスワード
アドレス:123@12 
パスワード:123456a
## 購入者用のメールアドレスとパスワード
アドレス:2@yoo
パスワード:123456a
## 購入用カードの番号・期限・セキュリティコード
購入用カードの番号:4242424242424242
期限:12/24
セキュリティコード:123

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
### [修正箇所]

- [ ] 必要な情報を適切に入力すると、商品の購入ができること
※現状、詳細ページに購入ボタンが表示されず購入ができません

上記のため、購入関係の挙動確認は次回以降にいたします。

修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/49669977/100427069-3c229a00-30d5-11eb-8c7c-bbfef2e12625.png)
